[project]
name = "flox"
version = "0.1.0"

description = "FLoX is a flexible, easy-to-deploy framework for serverless federated learning, with support for hierarchical and asynchronous federated learning."
readme = "README.md"

license = { file = "LICENSE" }
keywords = ["federated learning", "serverless", "machine learning"]

authors = [
    { name = "Nathaniel Hudson", email = "hudsonn@uchicago.edu" },
    { name = "Yadu Babuji", email = "yadunand@uchicago.edu" }
]

maintainers = [
    { name = "Nathaniel Hudson", email = "hudsonn@uchicago.edu" },
    { name = "Yadu Babuji", email = "yadunand@uchicago.edu" }
]

requires-python = ">=3.8"
dependencies = [
    "globus-compute-sdk",
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
    "torch",
    "pandas",
    "graphviz",
    "pygraphviz",
    "tqdm",
    "scipy",
]

[project.optional-dependencies]
dev = ["black", "coverage", "jupyterlab", "matplotlib", "numpy", "pytest", "seaborn", "tensorboard", "torchvision"]
monitoring = ["tensorboard"]
proxystore = ["proxystore[endpoints]"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.setuptools]
packages = ["flox"]
